# Generated by Django 4.1.4 on 2023-01-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationalcard', '0002_alter_card_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nationalcard.card'),
            preserve_default=False,
        ),
    ]
